# Generated by Django 3.2.16 on 2023-10-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_auto_20230929_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
