# Generated by Django 3.2.16 on 2023-10-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_alter_icecream_options'),
        ('ice_cream', '0005_auto_20230131_1130'),
    ]

    operations = [
    ]
