# Generated by Django 3.2.16 on 2023-10-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0006_merge_20231013_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('output_order',), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='icecream',
            options={'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
        migrations.AlterModelOptions(
            name='wrapper',
            options={'verbose_name': 'обёртка', 'verbose_name_plural': 'Обёртки'},
        ),
    ]
